mask_cut_gc: 0.
nside: 512
n_iter: 3
predir_in: '/mnt/extraspace/damonge/S8z_data/derived_products/'
predir_out: '/mnt/extraspace/damonge/S8z_data/derived_products/Cls_metacal_c'
bpw_edges: [0, 30, 60, 90, 120, 150, 180, 210, 240, 272, 309, 351, 398, 452, 513, 582, 661, 750, 852, 967, 1098, 1247, 1416, 1608, 1826, 2073, 2354, 2673, 3035, 3446, 3914, 4444, 5047, 5731, 6508, 7390, 8392, 9529, 10821, 12288]
recompute: False

masks:
  gc: des_clustering/mask_ns512.fits
  sh0: des_shear/map_metacal_bin0_w_ns512.fits
  sh1: des_shear/map_metacal_bin1_w_ns512.fits
  sh2: des_shear/map_metacal_bin2_w_ns512.fits
  sh3: des_shear/map_metacal_bin3_w_ns512.fits
  sh4: des_shear/map_metacal_bin4_w_ns512.fits

maps:
  gc0:
    mask: 'gc'
    type: 'gc'
    wcounts: 'des_clustering/map_counts_w_bin0_ns512.fits'
    dndz: 'des_clustering/dndz_bin0.txt'
    bias: 1.42
  gc1:
    mask: 'gc'
    type: 'gc'
    wcounts: 'des_clustering/map_counts_w_bin1_ns512.fits'
    dndz: 'des_clustering/dndz_bin1.txt'
    bias: 1.65
  gc2:
    mask: 'gc'
    type: 'gc'
    wcounts: 'des_clustering/map_counts_w_bin2_ns512.fits'
    dndz: 'des_clustering/dndz_bin2.txt'
    bias: 1.60
  gc3:
    mask: 'gc'
    type: 'gc'
    wcounts: 'des_clustering/map_counts_w_bin3_ns512.fits'
    dndz: 'des_clustering/dndz_bin3.txt'
    bias: 1.93
  gc4:
    mask: 'gc'
    type: 'gc'
    wcounts: 'des_clustering/map_counts_w_bin4_ns512.fits'
    dndz: 'des_clustering/dndz_bin4.txt'
    bias: 2.01
  sh0:
    mask: 'sh0'
    type: 'sh'
    prefix: 'des_shear/map_metacal_bin0_'
    sums: 'des_shear/sums_metacal_bin0.npz'
    nrot: 30
    dndz: 'des_shear/dndz_metacal_bin0.txt'
  sh1:
    mask: 'sh1'
    type: 'sh'
    prefix: 'des_shear/map_metacal_bin1_'
    sums: 'des_shear/sums_metacal_bin1.npz'
    nrot: 30
    dndz: 'des_shear/dndz_metacal_bin1.txt'
  sh2:
    mask: 'sh2'
    type: 'sh'
    prefix: 'des_shear/map_metacal_bin2_'
    sums: 'des_shear/sums_metacal_bin2.npz'
    nrot: 30
    dndz: 'des_shear/dndz_metacal_bin2.txt'
  sh3:
    mask: 'sh3'
    type: 'sh'
    prefix: 'des_shear/map_metacal_bin3_'
    sums: 'des_shear/sums_metacal_bin3.npz'
    nrot: 30
    dndz: 'des_shear/dndz_metacal_bin3.txt'

c_ells:
  - ['gc0', 'gc0']
  - ['gc1', 'gc1']
  - ['gc2', 'gc2']
  - ['gc3', 'gc3']
  - ['gc4', 'gc4']
  - ['gc0', 'sh0']
  - ['gc0', 'sh1']
  - ['gc0', 'sh2']
  - ['gc0', 'sh3']
  - ['gc1', 'sh0']
  - ['gc1', 'sh1']
  - ['gc1', 'sh2']
  - ['gc1', 'sh3']
  - ['gc2', 'sh0']
  - ['gc2', 'sh1']
  - ['gc2', 'sh2']
  - ['gc2', 'sh3']
  - ['gc3', 'sh0']
  - ['gc3', 'sh1']
  - ['gc3', 'sh2']
  - ['gc3', 'sh3']
  - ['gc4', 'sh0']
  - ['gc4', 'sh1']
  - ['gc4', 'sh2']
  - ['gc4', 'sh3']
  - ['sh0', 'sh0']
  - ['sh0', 'sh1']
  - ['sh0', 'sh2']
  - ['sh0', 'sh3']
  - ['sh1', 'sh1']
  - ['sh1', 'sh2']
  - ['sh1', 'sh3']
  - ['sh2', 'sh2']
  - ['sh2', 'sh3']
  - ['sh3', 'sh3']
