mask_cut_gc: 0.
nside: 512
n_iter: 3
predir_in: '/mnt/extraspace/damonge/S8z_data/derived_products/'
predir_out: '/mnt/extraspace/damonge/S8z_data/derived_products/Cls_im3shape'
bpw_edges: [0, 30, 60, 90, 120, 150, 180, 210, 240, 272, 309, 351, 398, 452, 513, 582, 661, 750, 852, 967, 1098, 1247, 1416, 1608, 1826, 2073, 2354, 2673, 3035, 3446, 3914, 4444, 5047, 5731, 6508, 7390, 8392, 9529, 10821, 12288]
recompute: False

masks:
  gc: des_clustering/mask_ns512.fits
  sh0: des_shear/map_im3shape_bin0_counts_w_ns512.fits
  sh1: des_shear/map_im3shape_bin1_counts_w_ns512.fits
  sh2: des_shear/map_im3shape_bin2_counts_w_ns512.fits
  sh3: des_shear/map_im3shape_bin3_counts_w_ns512.fits
  sh4: des_shear/map_im3shape_bin4_counts_w_ns512.fits

maps:
  gc0:
    mask: 'gc'
    type: 'gc'
    wcounts: 'des_clustering/map_counts_w_bin0_ns512.fits'
  gc1:
    mask: 'gc'
    type: 'gc'
    wcounts: 'des_clustering/map_counts_w_bin1_ns512.fits'
  gc2:
    mask: 'gc'
    type: 'gc'
    wcounts: 'des_clustering/map_counts_w_bin2_ns512.fits'
  gc3:
    mask: 'gc'
    type: 'gc'
    wcounts: 'des_clustering/map_counts_w_bin3_ns512.fits'
  gc4:
    mask: 'gc'
    type: 'gc'
    wcounts: 'des_clustering/map_counts_w_bin4_ns512.fits'
  sh0:
    mask: 'sh0'
    type: 'sh'
    prefix: 'des_shear/map_im3shape_bin0_'
    nrot: 10
  sh1:
    mask: 'sh1'
    type: 'sh'
    prefix: 'des_shear/map_im3shape_bin1_'
    nrot: 10
  sh2:
    mask: 'sh2'
    type: 'sh'
    prefix: 'des_shear/map_im3shape_bin2_'
    nrot: 10
  sh3:
    mask: 'sh3'
    type: 'sh'
    prefix: 'des_shear/map_im3shape_bin3_'
    nrot: 10

c_ells:
  - name: 'gc0_gc0'
    tracers: ['gc0', 'gc0']
  - name: 'gc1_gc1'
    tracers: ['gc1', 'gc1']
  - name: 'gc2_gc2'
    tracers: ['gc2', 'gc2']
  - name: 'gc3_gc3'
    tracers: ['gc3', 'gc3']
  - name: 'gc4_gc4'
    tracers: ['gc4', 'gc4']
  - name: 'gc0_sh0'
    tracers: ['gc0', 'sh0']
  - name: 'gc0_sh1'
    tracers: ['gc0', 'sh1']
  - name: 'gc0_sh2'
    tracers: ['gc0', 'sh2']
  - name: 'gc0_sh3'
    tracers: ['gc0', 'sh3']
  - name: 'gc1_sh0'
    tracers: ['gc1', 'sh0']
  - name: 'gc1_sh1'
    tracers: ['gc1', 'sh1']
  - name: 'gc1_sh2'
    tracers: ['gc1', 'sh2']
  - name: 'gc1_sh3'
    tracers: ['gc1', 'sh3']
  - name: 'gc2_sh0'
    tracers: ['gc2', 'sh0']
  - name: 'gc2_sh1'
    tracers: ['gc2', 'sh1']
  - name: 'gc2_sh2'
    tracers: ['gc2', 'sh2']
  - name: 'gc2_sh3'
    tracers: ['gc2', 'sh3']
  - name: 'gc3_sh0'
    tracers: ['gc3', 'sh0']
  - name: 'gc3_sh1'
    tracers: ['gc3', 'sh1']
  - name: 'gc3_sh2'
    tracers: ['gc3', 'sh2']
  - name: 'gc3_sh3'
    tracers: ['gc3', 'sh3']
  - name: 'gc4_sh0'
    tracers: ['gc4', 'sh0']
  - name: 'gc4_sh1'
    tracers: ['gc4', 'sh1']
  - name: 'gc4_sh2'
    tracers: ['gc4', 'sh2']
  - name: 'gc4_sh3'
    tracers: ['gc4', 'sh3']
  - name: 'sh0_sh0'
    tracers: ['sh0', 'sh0']
  - name: 'sh0_sh1'
    tracers: ['sh0', 'sh1']
  - name: 'sh0_sh2'
    tracers: ['sh0', 'sh2']
  - name: 'sh0_sh3'
    tracers: ['sh0', 'sh3']
  - name: 'sh1_sh1'
    tracers: ['sh1', 'sh1']
  - name: 'sh1_sh2'
    tracers: ['sh1', 'sh2']
  - name: 'sh1_sh3'
    tracers: ['sh1', 'sh3']
  - name: 'sh2_sh2'
    tracers: ['sh2', 'sh2']
  - name: 'sh2_sh3'
    tracers: ['sh2', 'sh3']
  - name: 'sh3_sh3'
    tracers: ['sh3', 'sh3']
